[package]
name = "scriba"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
askama = "0.14.0"
axum = "0.8.4"
chrono = { version = "0.4.41", features = ["serde"] }
regex = "1.11.2"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
tower-http = { version = "0.6.6", features = ["fs"] }
gray_matter = "0.3.2"

[dev-dependencies]
temp-env = "0.3.6"
